# Site wide configuration

title: Adriaan Dokter
description: personal webpage
logo: # 120x120 px default image used for Twitter summary card
teaser: 400x250.gif # 400x250 px default teaser image used in image archive grid
feature: Brent-banner-narrow.jpg
featuretext: landing.md
locale:
#url: http://localhost:4000
#url: http://adokter.github.io
url: http://adriaandokter.com

# Jekyll configuration

sass:
    sass_dir: _sass
    style: compressed
permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2
highlighter: rouge
gems:
  - jekyll-sitemap


# Site owner
owner:
  name: Adriaan Dokter
  email: adriaandokter@gmail.com
  github: https://www.github.com/adokter
  facebook: http://www.facebook.com/adriaan.dokter
  linkedin: https://www.linkedin.com/pub/adriaan-dokter/10/8b1/356
  google:
    ad-client: 
    ad-slot: 
  bio: 
  avatar: bio-photo.jpg # 160x160 px image for author byline
disqus-shortname:


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
